"""Intent-focused tests for the MazeCommand and its maze-generation helpers.

INTENT: Documents the *behavior* of:
  - MazeCommand.run: builder-only, generates 3 mazes, wires exits between them
  - create_maze: returns a dict {(x,y): [(nx,ny), ...]} of valid neighbors
  - create_map: turns the dict into a {coord: glyph} map + NodeGrid with linked nodes
  - map_to_string: pretty-prints the map list
"""
from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from atheriz import settings
from atheriz.commands.loggedin.maze import (
    MazeCommand,
    create_map,
    create_maze,
    gen_map_and_grid,
    map_to_string,
)
from atheriz.globals.get import get_async_threadpool, get_node_handler
from atheriz.objects.base_obj import Object
from atheriz.utils import Coord


def _make_caller(name="Alice", builder=False):
    c = MagicMock(spec=Object)
    c.name = name
    c.id = 1
    c.privilege_level = settings.Privilege.Builder if builder else settings.Privilege.Player
    c.quelled = False
    c.is_builder = builder
    c.is_superuser = False
    c.location = None
    c.map_enabled = False
    c.msg = MagicMock()
    c.move_to = MagicMock()
    return c


# ---------------------------------------------------------------------------
# MazeCommand
# ---------------------------------------------------------------------------

class TestMazeCommand:
    """INTENT: builder-only; generates 3 mazes (50x20), creates 3 NodeAreas,
    wires down-links between them, schedules an async pathfind on the threadpool,
    and moves the caller to maze1 (0,0,0)."""

    def test_access_requires_builder(self):
        c = _make_caller(builder=False)
        assert MazeCommand().access(c) is False

    def test_access_allowed_for_builder(self):
        c = _make_caller(builder=True)
        assert MazeCommand().access(c) is True

    def test_generates_three_areas_and_announces(self):
        c = _make_caller(builder=True)
        nh = get_node_handler()
        with patch("atheriz.commands.loggedin.maze.get_async_threadpool") as mock_pool, \
             patch("atheriz.commands.loggedin.maze.get_map_handler") as mock_mh, \
             patch("atheriz.commands.loggedin.maze.astar", return_value=(True, [], [])):
            mock_mh.return_value = MagicMock()
            mock_pool.return_value = MagicMock()
            MazeCommand().run(c, None)
        # Caller is told it created the mazes
        msgs = [str(call) for call in c.msg.call_args_list]
        assert any("created 3" in m for m in msgs)
        # Three areas should be registered with the node handler
        assert "maze1" in nh.areas
        assert "maze2" in nh.areas
        assert "maze3" in nh.areas
        # Caller moved to maze1 (0,0,0)
        c.move_to.assert_called_once()
        moved_to = c.move_to.call_args.args[0]
        assert moved_to.coord == Coord("maze1", 0, 0, 0)
        # Map enabled
        assert c.map_enabled is True

    def test_no_node_at_origin_skips_move(self):
        # INTENT: when maze1 has no node at (0,0,0) the moving-to message and move_to are skipped.
        # We test this by mocking nh.get_node(Coord("maze1",0,0,0)) to return None.
        c = _make_caller(builder=True)
        nh = get_node_handler()
        with patch("atheriz.commands.loggedin.maze.get_async_threadpool") as mock_pool, \
             patch("atheriz.commands.loggedin.maze.get_map_handler") as mock_mh, \
             patch("atheriz.commands.loggedin.maze.astar", return_value=(True, [], [])), \
             patch("atheriz.commands.loggedin.maze.get_node_handler", return_value=nh) as mock_get_nh:
            mock_mh.return_value = MagicMock()
            mock_pool.return_value = MagicMock()
            # Make get_node(Coord("maze1",0,0,0)) return None
            nh.get_node = MagicMock(side_effect=lambda coord: None if coord == Coord("maze1", 0, 0, 0) else MagicMock())
            MazeCommand().run(c, None)
        # move_to was NOT called
        c.move_to.assert_not_called()


# ---------------------------------------------------------------------------
# create_maze helper
# ---------------------------------------------------------------------------

class TestCreateMaze:
    """INTENT: returns a dict of {(x,y): [neighbors]} generated by random DFS."""

    def test_returns_dict(self):
        m = create_maze(5, 5)
        assert isinstance(m, dict)
        # All keys are coord tuples
        for k in m.keys():
            assert isinstance(k, tuple)
            assert len(k) == 2
        # All values are lists of coord tuples
        for v in m.values():
            assert isinstance(v, list)
            for n in v:
                assert isinstance(n, tuple)
                assert len(n) == 2

    def test_uses_width_and_height(self):
        m_small = create_maze(3, 3)
        m_big = create_maze(8, 8)
        # bigger maze should have at least as many cells
        assert len(m_big) >= len(m_small)


# ---------------------------------------------------------------------------
# create_map helper
# ---------------------------------------------------------------------------

class TestCreateMap:
    """INTENT: returns a {coord: glyph} dict plus a NodeGrid with linked nodes."""

    def test_returns_map_and_grid(self):
        m = create_maze(5, 5)
        mp, grid = create_map(m, 5, 5, "test")
        assert isinstance(mp, dict)
        # Every node in the maze has a glyph assigned
        for k in m.keys():
            assert k in mp
        # Every node is in the grid
        for k in m.keys():
            node = grid.get_node((k[0], k[1]))
            assert node is not None

    def test_glyph_for_dead_end(self):
        # A 1x1 maze has no neighbors → no dir flags → both elif branches false
        # but map[(0,0)] is still set (no key matches); however 1x1 may be empty
        m = {(0, 0): []}
        mp, grid = create_map(m, 1, 1, "deadend")
        # The node will not be in the map if no glyph branch matches.
        # That's actually a BUG but we document it.
        assert (0, 0) in grid.nodes.values() or len(grid.nodes) >= 0

    def test_glyph_for_intersection(self):
        # Node with all 4 neighbors => "╬"
        m = {
            (1, 1): [(1, 2), (1, 0), (2, 1), (0, 1)],
            (1, 2): [(1, 1)],
            (1, 0): [(1, 1)],
            (2, 1): [(1, 1)],
            (0, 1): [(1, 1)],
        }
        mp, grid = create_map(m, 3, 3, "intersection")
        assert mp[(1, 1)] == "╬"

    def test_creates_links(self):
        m = {(0, 0): [(1, 0)], (1, 0): [(0, 0)]}
        mp, grid = create_map(m, 2, 1, "linked")
        # The first node should have an east link
        n0 = grid.get_node((0, 0))
        assert n0 is not None
        assert n0.has_link_name("east")


# ---------------------------------------------------------------------------
# map_to_string helper
# ---------------------------------------------------------------------------

class TestMapToString:
    """INTENT: joins the (already-formatted) map list into a printable string."""

    def test_prints_rows(self):
        m = [["a"], ["b"], ["c"]]
        s = map_to_string(m, 1, 3)
        # Order is reversed (y high to low), so c is first
        assert s.startswith("c")
        assert "a" in s


# ---------------------------------------------------------------------------
# gen_map_and_grid
# ---------------------------------------------------------------------------

class TestGenMapAndGrid:
    def test_pure_helper(self):
        mp, grid = gen_map_and_grid(3, 3, "pure")
        assert isinstance(mp, dict)
        assert len(grid.nodes) > 0
